ALTER TABLE app_users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE enterprises ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE enterprises ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE enterprises ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE enterprises ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE appointments ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE customers ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE service_offerings ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE service_offerings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE service_offerings ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE service_offerings ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE working_hours ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE working_hours ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE working_hours ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE working_hours ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
